description: OPT_DEBUG_JOB

target:
  service: amlk8s
  # run "amlt target list amlk8s" to list the names of available AMLK8s targets
  name: itphyperdgx2cl1
  vc: hai3

# target:
#   service: amlk8s
#   # run "amlt target list amlk8s" to list the names of available AMLK8s targets
#   name: itplabrr1cl1
#   vc: resrchvc

# target:
#   service: amlk8s
#   # run "amlt target list amlk8s" to list the names of available AMLK8s targets
#   name: itpeastusv100cl2
#   vc: resrchvc

environment:
  image: metaseq-opt:latest
  username: metaseqopt
  registry: metaseqopt.azurecr.io
  setup:
    - sudo pip install -e .
    - sudo python setup.py install
    
code:
  # local directory of the code. this will be uploaded to the server.
  # $CONFIG_DIR is expanded to the directory of this config file
  local_dir: ../../../../

data:
  remote_dir: e2e_lm_dataset
  storage_id: input_data

storage:
  input_data:
    storage_account_name: sahagar
    container_name: data
    mount_dir: /mnt/input_data_dir

  output:
    storage_account_name: sahagar
    container_name: amulet-output
    mount_dir: /mnt/output_dir

jobs:
  - name: OPT_DEBUG_JOB
    sku: 4xG16
    command:
      # code_dir=/tmp/code
      - set -ex
      - sleep infinity
    process_count_per_node: 0